name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: |
          # Baixa o código usando curl e tar
          mkdir -p $GITHUB_WORKSPACE/repo
          curl -sL https://github.com/${{ github.repository }}/archive/refs/heads/${{ github.ref_name }}.tar.gz | tar xz --strip-components=1 -C $GITHUB_WORKSPACE/repo
          cd $GITHUB_WORKSPACE/repo
          
      - name: Setup Node.js
        run: |
          # Instala o Node.js usando nvm (Node Version Manager)
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18
          node --version
          npm --version
          
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/repo
          npm install --no-audit --no-fund
        
      - name: Build
        working-directory: $GITHUB_WORKSPACE/repo
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          npm run build
          touch dist/.nojekyll
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Deploy to gh-pages
        run: |
          cd $GITHUB_WORKSPACE/repo
          
          # Configura o token de autenticação
          TOKEN=${{ secrets.GITHUB_TOKEN || secrets.DEPLOY_TOKEN }}
          
          # Configura o repositório remoto com autenticação
          git remote set-url origin https://x-access-token:$TOKEN@github.com/$GITHUB_REPOSITORY.git
          
          # Cria ou limpa o branch gh-pages
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git rm -rf .
          else
            git checkout --orphan gh-pages
          fi
          
          # Copia os arquivos de build
          cp -r dist/* .
          
          # Commit e push
          git add -A
          git commit -m "Deploy para GitHub Pages" --allow-empty
          git push origin gh-pages --force