name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --no-audit
        
      - name: Build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          npm run build
          touch dist/.nojekyll
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Deploy to gh-pages
        run: |
          # Configura o token de autenticação
          TOKEN=${{ secrets.GITHUB_TOKEN || secrets.DEPLOY_TOKEN }}
          
          # Configura o repositório remoto com autenticação
          git remote set-url origin https://x-access-token:$TOKEN@github.com/$GITHUB_REPOSITORY.git
          
          # Cria ou limpa o branch gh-pages
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git rm -rf .
          else
            git checkout --orphan gh-pages
          fi
          
          # Copia os arquivos de build
          cp -r dist/* .
          
          # Commit e push
          git add -A
          git commit -m "Deploy para GitHub Pages" --allow-empty
          git push origin gh-pages --force
